version: '3.8'

services:
  # PostgreSQL Database (Dev)
  postgres:
    image: postgres:15-alpine
    container_name: k-kits-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: k_kits_user
      POSTGRES_PASSWORD: k_kits_password
      POSTGRES_DB: k_kits_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

  # Redis Cache (Dev)
  redis:
    image: redis:7-alpine
    container_name: k-kits-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data

volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local
